### ISSUE TITLE
Breaking change in 3.9.0

### ISSUE THREAD

**Issue by jcoyne** [ViewComponent/view_component#1959]
Use view_components to renders HTML in a json field (so the request format is 'json').  After upgrading to 3.9.0 (from 3.8.0) I get this error:

```
      Failure/Error: <textarea id='sul-embed-iframe-code' data-behavior='iframe-code'><%= render IframeComponent.new(viewer:) %></textarea>

      NoMethodError:
        undefined method `html?' for "json":String
      # ./app/components/embed_this_form_component.html.erb:30:in `call'
      # ./spec/components/embed_this_form_component_spec.rb:32:in `block (4 levels) in <main>'
      # ./spec/components/embed_this_form_component_spec.rb:31:in `block (3 levels) in <main>'
```

I believe this was cause by this change https://github.com/ViewComponent/view_component/pull/1950/files#diff-b69c75ffd85596e0b5fca1327059ecf3b2930f3f77004c78a268fa85e8ec8d9eR311

**Comment by reeganviljoen** [comment]
this is a duplicate of #1955 so I will close this issue, If you want to track the progress of this bug please refer to the original issue

**Comment by jcoyne** [comment]
@reeganviljoen I don't think it is a duplicate necessarily. #1955 is "when the input is an Integer", and there is no integer input here.  Perhaps #1955 needs to be amended to be more general?

**Comment by reeganviljoen** [comment]
@jcoyne the underlying issue is the same, so can I please ask you to add your context to teh original issue indicating that this happens with json types to

**Comment by reeganviljoen** [comment]
@jcoyne I have also refactored the method to be type safe, as-well as to use json in a test
