### ISSUE TITLE
#maybe_escape_html chokes when input is an Integer

### ISSUE THREAD

**Issue by tmaier** [ViewComponent/view_component#1955]
My CI pipeline suddenly fails when upgrading from 3.8.0 to 3.9.0.

I believe this is related to #1950. 

### Steps to reproduce

- It seems like my code hands over an integer to [`#maybe_escape_html`](https://github.com/ViewComponent/view_component/blob/c8462c2113ca1771b681fc89eb025d8e8b685727/lib/view_component/base.rb#L312C1-L313C1). This is not expected by the code.

### Expected behavior

No Exception

### Actual behavior

```
     NoMethodError:
       undefined method `empty?' for 2016:Integer
             return text if text.nil? || text.empty?
                                             ^^^^^^^
     # /usr/local/bundle/ruby/3.1.0/gems/view_component-3.9.0/lib/view_component/base.rb:312:in `maybe_escape_html'
     # /usr/local/bundle/ruby/3.1.0/gems/view_component-3.9.0/lib/view_component/base.rb:326:in `safe_render_template_for'
     # /usr/local/bundle/ruby/3.1.0/gems/view_component-3.9.0/lib/view_component/base.rb:109:in `render_in'
```

**first thoughts**:

- One could convert the `text` to string first before calling `#empty?`, similar to how `Slot#html_safe?` works. See <https://github.com/ViewComponent/view_component/blob/main/lib/view_component/slot.rb#L99C6-L99C6>
  - Note that `to_s.html_safe?` should actually be not necessary, since Rails implements `html_safe?` on the `Numberic` and `Object` classes

### System configuration
**Rails version**: 7.0.8

**Ruby version**: 3.1.4

**Gem version**: 3.9.0

**Comment by reeganviljoen** [comment]
@tmaier i aprreciate your speedy bug report, could you possibly add a failing test case as a pr so we can fix this bug

**Comment by natematykiewicz** [comment]
Similarly, I've got a component that now errors when trying to render a slot.

```ruby
class ArtworkLinkComponent < ViewComponent::Base
  renders_one :empty_state

  def initialize(attachment:, variation:, url:)
    @attachment = attachment
    @variation = variation
    @url = url
  end

  def call
    return empty_state unless @attachment.attached?

    link_to @url do
      image_tag @attachment.variant(@variation)
    end
  end
end

render ArtworkLinkComponent.new(attachment: user.avatar, variation: :thumbnail, url: user_url(user)) do |component|
  component.with_empty_state do
    'No avatar'
  end
end
```

This works fine on 3.8.0 but errors on 3.9.0. This is because [here](https://github.com/ViewComponent/view_component/blob/c8462c2113ca1771b681fc89eb025d8e8b685727/lib/view_component/base.rb#L312), `text` is a `ViewComponent::Slot`, which does not have an `empty?` method.

This results in:
```
NoMethodError:
  undefined method `empty?' for nil:NilClass

# .gems/ruby/3.2.0/gems/view_component-3.9.0/lib/view_component/slot.rb:95:in `public_send'
# .gems/ruby/3.2.0/gems/view_component-3.9.0/lib/view_component/slot.rb:95:in `method_missing'
# .gems/ruby/3.2.0/gems/view_component-3.9.0/lib/view_component/base.rb:312:in `maybe_escape_html'
# .gems/ruby/3.2.0/gems/view_component-3.9.0/lib/view_component/base.rb:326:in `safe_render_template_for'
# .gems/ruby/3.2.0/gems/view_component-3.9.0/lib/view_component/base.rb:109:in `render_in'
```

I guess that means `ViewComponent::Slot`'s `@__vc_component_instance` is nil?

**Comment by natematykiewicz** [comment]
I just noticed if I add a `.to_s`, everything works fine:

```ruby
return empty_state.to_s unless @attachment.attached?
                  ^^^^^ Added this
```

**Comment by reeganviljoen** [comment]
@tmaier @natematykiewicz thank you for letting us know, I am investigating this issue

**Comment by jcoyne** [comment]
Also keep in mind that a user may be producing HTML even if the request format isn't `#html?`.   For example I may request a json format but I'm using ViewComponent to render HTML into one of the fields in the json.   So this conditional my need to change: https://github.com/ViewComponent/view_component/pull/1950/files#diff-b69c75ffd85596e0b5fca1327059ecf3b2930f3f77004c78a268fa85e8ec8d9eR311

**Comment by camertron** [comment]
@jcoyne right I get that, but there's no way for the framework to know what format to render unless it checks `request.html?`. The only way to ensure safety for eg. JSON responses is for the `#call` method to return escaped HTML when necessary. In other words, I don't think the framework should be responsible for escaping in these cases.

**Comment by jcoyne** [comment]
@camertron Shoudn't it always work consistently?  It's more difficult to reason about if it works differently in different contexts.

**Comment by camertron** [comment]
@jcoyne how would you expect the framework to behave in this case? It could always escape, but then output from template engines like jbuilder will get escaped too, which I would argue is pretty surprising and undesirable. We could add a parameter somewhere, but it's not clear where it should go. Any ideas?

**Comment by reeganviljoen** [comment]
> @jcoyne how would you expect the framework to behave? It could always escape, but then output from template engines like jbuilder will get escaped too, which I would argue is pretty surprising and undesirable. We could add a parameter somewhere, but it's not clear where it should go. Any ideas?

Just my thoughts we could add this together with actual support for other mime types such as json

**Comment by jcoyne** [comment]
@camertron I think the way that would be most explicit would be to add a method like `render_with_escaping` to be added as a controller method and steer people to use that if they render directly from a controller.

**Comment by joelhawksley** [comment]
@jcoyne I disagree. It's a Rails convention to escape unsafe input by default. I'd instead argue for `render_without_escaping`, if we were to go that route.

**Comment by jcoyne** [comment]
@joelhawksley The problem I have right now is that it's not escaping html by default for me (because I'm putting it in a json request).   I need a way to do the escaping in a way that I do not have control of with the current implementation.

**Comment by camertron** [comment]
@reeganviljoen true, but we would still have the issue of rendering content for one MIME type for use in another.

> The problem I have right now is that it's not escaping html by default for me.

@jcoyne I don't understand why this problem has arisen as a result of the change released in v3.9.0, since the original (unsafe) behavior was no automatic escaping by default as well. In other words, you should have had this problem in all previous versions of the framework.

I agree with @joelhawksley that we should escape by default, but only when generating HTML. Performing HTML escaping in non-HTML contexts is surprising and not appropriate IMO. The underlying issue here is that template engines like ERB escape HTML automatically, but in the case of content returned from a `#call` method, there is no template engine at play. Since the component creator is effectively providing their own template engine, it stands to reason they would also be responsible for any escaping. I added automatic escaping in v3.9.0 just in case someone forgets to do it themselves, which mimics what the template engine would do. The warning that gets printed should alert component authors to fix any HTML safety issues, since `#call` methods should always return HTML-safe strings. In other words, the framework should have no need to escape anything if `#call` returns sanitized output.

> I need a way to do the escaping in a way that I do not have control of with the current implementation.

Is it possible to call `#html_escape` or `#html_safe` in your `#call` method, or when the JSON response is being constructed? I'd say you have exactly the same amount of control as you have with the current implementations of ERB, Slim, HAML, etc.

**Comment by jcoyne** [comment]
> I don't understand why this problem has arisen as a result of the change released in v3.9.0, since the original (unsafe) behavior was no automatic escaping by default as well. In other words, you should have had this problem in all previous versions of the framework.

What I mean to say is that 3.9.0 is both broken (raises an error), but even with that fixed, it doesn't do the expected escaping for my use case.

**Comment by camertron** [comment]
> What I mean to say is that 3.9.0 is ... broken (raises an error)

Ok gotcha. That error should be fixed in the upcoming 3.10.0 release, which I'm preparing now.

> but even with that fixed, it doesn't do the expected escaping for my use case.

Sure, but the framework has never performed the kind of escaping your use case expects. Unless I'm really missing something, I think the right thing to do is to use the HTML escaping mechanisms already available to you, eg. `#html_safe` and `#html_escape`.

**Comment by jcoyne** [comment]
> I think the right thing to do is to use the HTML escaping mechanisms already available to you

I'm just rendering a component to a string and then sticking that string into a json object.   It seems weird that I have to do some special escaping when I render a component to a string that is unnecessary when I render it in a controller (with html format).   This is coming back to consistency. It would be much simpler for the user if rendering a component that produces html, always produces the same output whether rendered to a string, mailer, turbo stream broadcast, or in a controller. I think it's unfortunate that you'd need to remember to do custom escaping in 3/4 of those cases.

**Comment by camertron** [comment]
Alright @jcoyne I hear what you're saying 😄 Let's move this discussion elsewhere, since it's really a feature request/bug report that's only tangentially related to this `#maybe_escape_html` issue. Would you mind filing a separate issue?

**Comment by camertron** [comment]
This should be fixed in v3.10.0 🎉
