### ISSUE TITLE
NoMethodError: undefined method `html?' for "json":String

### ISSUE THREAD

**Issue by jcoyne** [ViewComponent/view_component#1971]
This is a regression related to #1955.  This works fine in 3.8.0, but breaks in 3.9.0 and remains broken with 3.10.0

I see this error when running a test of a component using rspec:

```
  1) EmbedPanelComponent header has the panel title
     Failure/Error: <textarea id='sul-embed-iframe-code' data-behavior='iframe-code'><%= render IframeComponent.new(viewer:) %></textarea>

     NoMethodError:
       undefined method `html?' for "json":String
     # /Users/jcoyne85/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/view_component-3.10.0/lib/view_component/base.rb:320:in `maybe_escape_html'
     # /Users/jcoyne85/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/view_component-3.10.0/lib/view_component/base.rb:335:in `safe_render_template_for'
     # /Users/jcoyne85/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/view_component-3.10.0/lib/view_component/base.rb:108:in `render_in'
     # /Users/jcoyne85/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionview-7.1.2/lib/action_view/helpers/rendering_helper.rb:42:in `render'
     # /Users/jcoyne85/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/view_component-3.10.0/lib/view_component/base.rb:204:in `render'
     # ./app/components/embed_this_form_component.html.erb:30:in `call'
     # /Users/jcoyne85/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/view_component-3.10.0/lib/view_component/compiler.rb:126:in `render_template_for'
     # /Users/jcoyne85/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/view_component-3.10.0/lib/view_component/base.rb:333:in `safe_render_template_for'
     # /Users/jcoyne85/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/view_component-3.10.0/lib/view_component/base.rb:108:in `render_in'
     # /Users/jcoyne85/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionview-7.1.2/lib/action_view/helpers/rendering_helper.rb:42:in `render'
     # /Users/jcoyne85/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/view_component-3.10.0/lib/view_component/base.rb:204:in `render'
     # ./app/components/embed_panel_component.html.erb:11:in `call'
     # /Users/jcoyne85/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/view_component-3.10.0/lib/view_component/compiler.rb:126:in `render_template_for'
     # /Users/jcoyne85/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/view_component-3.10.0/lib/view_component/base.rb:333:in `safe_render_template_for'
     # /Users/jcoyne85/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/view_component-3.10.0/lib/view_component/base.rb:108:in `render_in'
     # /Users/jcoyne85/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionview-7.1.2/lib/action_view/helpers/rendering_helper.rb:42:in `render'
     # /Users/jcoyne85/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/view_component-3.10.0/lib/view_component/test_helpers.rb:50:in `render_inline'
     # ./spec/components/embed_panel_component_spec.rb:7:in `block (2 levels) in <top (required)>'
```

**Comment by jcoyne** [comment]
It appears that the `request` method that is expected by `maybe_escape_html` is a custom method that I have been using in my component.

```
   319|     def maybe_escape_html(text)
=> 320|       debugger
   321|       return text if request && !request.format.html?
   322|       return text if text.blank?
   323|
   324|       if text.html_safe?
=>#0	ViewComponent::Base#maybe_escape_html(text="<iframe src=\"http://test.host/iframe?ur...) at ~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/view_component-3.10.0/lib/view_component/base.rb:320
  #1	ViewComponent::Base#safe_render_template_for(variant=nil) at ~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/view_component-3.10.0/lib/view_component/base.rb:336
  # and 79 frames (use `bt' command for all frames)
(rdbg) request
#<Embed::Request:0x0000000106883e50 @params={:url=>"http://purl.stanford.edu/abc123"}>
(ruby) method(:request)
#<Method: IframeComponent#request(...) /Users/jcoyne85/workspace/sul-dlss/sul-embed/app/components/iframe_component.rb:9>
(rdbg)
```

**Comment by boardfish** [comment]
I wonder if there's anything we can do to signal that `request` is a reserved word? IIRC, we already warn/error for slot overrides on a bunch of things, not sure if this is among them.
