### ISSUE TITLE
Implicit locale in file name doesn't work anymore

### ISSUE THREAD

**Issue by harm-matthias-harms** [ViewComponent/view_component#2113]
### Steps to reproduce

Create a template file with i18n specified in the name, e.g. `imprint_component.de.html.erb` This worked with `view_component < 3.15`. I guess it broke with the format support.

### Expected behavior

The template is found and rendered.
https://guides.rubyonrails.org/i18n.html#localized-views

### Actual behavior

`NameError` thrown

**Backtrace**:
```
NameError:
  undefined local variable or method `call_de' for class Common::Pdf::SpecialPages::ImprintComponent
# ./vendor/bundle/ruby/3.3.0/gems/view_component-3.15.1/lib/view_component/inline_template.rb:10:in `method_missing'
# ./app/components/common/pdf/special_pages/imprint_component.de.html.haml:in `compile_to_component'
# ./vendor/bundle/ruby/3.3.0/gems/view_component-3.15.1/lib/view_component/template.rb:48:in `class_eval'
# ./vendor/bundle/ruby/3.3.0/gems/view_component-3.15.1/lib/view_component/template.rb:48:in `compile_to_component'
# ./vendor/bundle/ruby/3.3.0/gems/view_component-3.15.1/lib/view_component/compiler.rb:59:in `block (2 levels) in define_render_template_for'
# ./vendor/bundle/ruby/3.3.0/gems/view_component-3.15.1/lib/view_component/compiler.rb:58:in `synchronize'
# ./vendor/bundle/ruby/3.3.0/gems/view_component-3.15.1/lib/view_component/compiler.rb:58:in `block in define_render_template_for'
# ./vendor/bundle/ruby/3.3.0/gems/view_component-3.15.1/lib/view_component/compiler.rb:57:in `each'
# ./vendor/bundle/ruby/3.3.0/gems/view_component-3.15.1/lib/view_component/compiler.rb:57:in `define_render_template_for'
# ./vendor/bundle/ruby/3.3.0/gems/view_component-3.15.1/lib/view_component/compiler.rb:40:in `compile'
# ./vendor/bundle/ruby/3.3.0/gems/view_component-3.15.1/lib/view_component/base.rb:569:in `compile'
# ./vendor/bundle/ruby/3.3.0/gems/view_component-3.15.1/lib/view_component/engine.rb:84:in `each'
# ./vendor/bundle/ruby/3.3.0/gems/view_component-3.15.1/lib/view_component/engine.rb:84:in `block (2 levels) in <class:Engine>'
# ./vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.4/lib/active_support/lazy_load_hooks.rb:99:in `instance_eval'
# ./vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.4/lib/active_support/lazy_load_hooks.rb:99:in `block in execute_hook'
# ./vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.4/lib/active_support/lazy_load_hooks.rb:87:in `with_execution_control'
# ./vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.4/lib/active_support/lazy_load_hooks.rb:92:in `execute_hook'
# ./vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.4/lib/active_support/lazy_load_hooks.rb:78:in `block in run_load_hooks'
# ./vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.4/lib/active_support/lazy_load_hooks.rb:77:in `each'
# ./vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.4/lib/active_support/lazy_load_hooks.rb:77:in `run_load_hooks'
# ./vendor/bundle/ruby/3.3.0/gems/railties-7.1.4/lib/rails/application/finisher.rb:93:in `block in <module:Finisher>'
# ./vendor/bundle/ruby/3.3.0/gems/railties-7.1.4/lib/rails/initializable.rb:32:in `instance_exec'
# ./vendor/bundle/ruby/3.3.0/gems/railties-7.1.4/lib/rails/initializable.rb:32:in `run'
# ./vendor/bundle/ruby/3.3.0/gems/railties-7.1.4/lib/rails/initializable.rb:61:in `block in run_initializers'
# ./vendor/bundle/ruby/3.3.0/gems/railties-7.1.4/lib/rails/initializable.rb:60:in `run_initializers'
# ./vendor/bundle/ruby/3.3.0/gems/railties-7.1.4/lib/rails/application.rb:426:in `initialize!'
# ./config/environment.rb:7:in `<top (required)>'
# ./spec/rails_helper.rb:6:in `<top (required)>'
No examples found.
```

### System configuration
**Rails version**:
7.1.4

**Ruby version**:
3.3.5

**Gem version**:
3.15.1

**Comment by joelhawksley** [comment]
@harm-matthias-harms thanks for the report- looks like we are missing a test case in our suite. Would you be willing to open a PR with a failing test for this case?

**Comment by chloe-meister** [comment]
@joelhawksley I stumbled upon this today too, and it's because of the refactor to `@call_method_name`. For localised files, it's trying to define `call_de` instead of `call` because it now uses the format from the compiler.
For localised files, the format is `<locale>html` instead of `html` only.

One very easy way to see the error is to add a `component.de.html.erb` file in `test/sandbox/app/components` and to run the test suite, as it'll quickly crash with the above error.

I have such a file on a fork if you like, I can open a PR if needed.

**Comment by joelhawksley** [comment]
Closed by https://github.com/ViewComponent/view_component/pull/2118/
