### PR TITLE
Update testing.md

### LINKED ISSUE #1690: RSpec: undefined local variable or method `controller' when upgrading to 3.0.0.rc-4
With the following RSpec configuration:

```ruby
RSpec.configure do |config|
  config.include ViewComponent::TestHelpers, type: :component
  config.include ViewComponent::SystemTestHelpers, type: :component
  config.include Capybara::RSpecMatchers, type: :component

  config.include Devise::Test::ControllerHelpers, type: :component
  config.before(:each, type: :component) do
    @request = controller.request
  end
end
```

As recommended at https://viewcomponent.org/guide/testing.html#rspec-configuration

Under version 2.82.0 my specs work as expected.

After upgrading to 3.0.0.rc-4 I get the following error in all my specs:

```NameError: undefined local variable or method `controller' for #<RSpec::ExampleGroups::BadgeComponent "renders a primary badge" (./spec/components/badge_component_spec.rb:13)>```

### System configuration
**Rails version**: 7.0.4.3

**Ruby version**: 3.2.1

**Gem version**: 3.0.0.rc-4

### PR DESCRIPTION
**Pull request by steveclarke**
Close #1690

### CODE REVIEW

**Comment by Spone** [comment]
Thanks! :ok_hand:
