### ISSUE TITLE
RSpec: undefined local variable or method `controller' when upgrading to 3.0.0.rc-4

### ISSUE THREAD

**Issue by steveclarke** [ViewComponent/view_component#1690]
With the following RSpec configuration:

```ruby
RSpec.configure do |config|
  config.include ViewComponent::TestHelpers, type: :component
  config.include ViewComponent::SystemTestHelpers, type: :component
  config.include Capybara::RSpecMatchers, type: :component

  config.include Devise::Test::ControllerHelpers, type: :component
  config.before(:each, type: :component) do
    @request = controller.request
  end
end
```

As recommended at https://viewcomponent.org/guide/testing.html#rspec-configuration

Under version 2.82.0 my specs work as expected.

After upgrading to 3.0.0.rc-4 I get the following error in all my specs:

```NameError: undefined local variable or method `controller' for #<RSpec::ExampleGroups::BadgeComponent "renders a primary badge" (./spec/components/badge_component_spec.rb:13)>```

### System configuration
**Rails version**: 7.0.4.3

**Ruby version**: 3.2.1

**Gem version**: 3.0.0.rc-4

**Comment by Spone** [comment]
It's related to https://github.com/ViewComponent/view_component/pull/1675

I think we forgot to update the docs. Would you mind opening a PR to fix the docs?

**Comment by steveclarke** [comment]
Thanks @Spone that worked! I've submitted a pull-request with the updated documentation.

**Comment by boardfish** [comment]
Also, a patch for ViewComponent V2 that makes it available there as well:

```rb
# spec_ or rails_helpers.rb, in your RSpec config block
  # Remove this upon V3 upgrade
  module VCTestControllerPatch
    extend ActiveSupport::Concern

    included do
      alias_method :vc_test_controller, :controller
    end
  end
  config.include VCTestControllerPatch, type: :component
```

Ideally it would ouright remove the `controller` method in component specs, but your CI should catch any tests that begin to fail because they're still using `controller` when you come to upgrade to V3.

**Comment by Spone** [comment]
@boardfish what do you think about compiling all advice and code samples related to v2 > v3 upgrade and publishing them in a dedicated page in the docs?
